name: Generate README

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
#     - name: Install dependencies
#       run: |
#         python -m pip install --upgrade pip
#         if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Generate the README
      run: python generate.py
    - name: Commit the generated file
      uses: EndBug/add-and-commit@v7
      with:
        add: ./README.md
        message: 'Commit for generated README (from GitHub Actions)'
